Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,15 +35,26 @@ jobs:
       # Note: Adjusting hardware configurations like RAM and CPU must be done outside of GitHub Actions and directly on the host or VM.
 
     - name: Start Ngrok Tunnel
-      run: .\ngrok\ngrok.exe tcp 3389 > ngrok_output.log & Start-Sleep -Seconds 10
+      run: .\ngrok\ngrok.exe tcp 3389 > ngrok_output.log 2>&1 & Start-Sleep -Seconds 15
+
+    - name: Display Ngrok Output
+      run: |
+        $output = Get-Content ngrok_output.log
+        Write-Output "Ngrok output:"
+        Write-Output $output
 
     - name: Get Ngrok Public URL
       run: |
         $output = Get-Content ngrok_output.log
+        if ($null -eq $output) {
+          Write-Error "Ngrok output is empty or not found."
+          exit 1
+        }
         $matches = [regex]::Matches($output, 'tcp://[^\s]+')
         if ($matches.Count -gt 0) {
           $public_url = $matches[0].Value
-          echo "Ngrok tunnel URL: $public_url"
+          Write-Output "Ngrok tunnel URL: $public_url"
         } else {
-          echo "Failed to get Ngrok URL"
+          Write-Error "Failed to get Ngrok URL from output."
+          exit 1
         }
